services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama run llama3 && tail -f /dev/null"

  api:
    build:
      context: .
    container_name: tds-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /bin/bash
    command: >
      -c "echo '📡 Scraping discourse...' &&
          python scripts/scrape_discourse.py &&
          echo '🔎 Building vector store...' &&
          python scripts/build_vector_store.py &&
          echo '🚀 Starting FastAPI...' &&
          uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  ollama-data:
